eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: master
          uri: http://localhost:8080
          predicates:
            - Path=/master/**
        - id: users
          uri: http://localhost:8081
          predicates:
            - Path=/user/**
        - id: partner
          uri: http://localhost:8085
          predicates:
            - Path=/partners/**,/partner-**
