eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: master
          uri: http://localhost:8080
          predicates:
            - Path=/master/**
        - id: partner
          uri: http://localhost:8081
          predicates:
            - Path=/partners/**,/partner-**
        - id: service
          uri: http://localhost:8082
          predicates:
            - Path=/service/**,/sero/**,/seot/**,/sowo/**,/premi/**,/claim-asset/**