eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=smartdrive;encrypt=true;trustServerCertificate=true;
    username: sa
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
application:
  config:
    master-url: http://localhost:8222/master
#    consumer:
#      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer